# /etc/pacman.conf

[options]
HoldPkg           = pacman glibc
CleanMethod       = KeepInstalled KeepCurrent
Architecture      = auto
ParallelDownloads = 10
DownloadUser      = alpm

Color
CheckSpace
VerbosePkgLists

SigLevel          = Required DatabaseNever
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[custom]
SigLevel = Required DatabaseOptional
Server = file:///var/cache/pacman/custom

#[example]
#SigLevel = Required
#Server = https://www.example.com/archlinux/$repo/os/$arch
