#!/hint/bash

# Copies existing, hopefully known-good, configs to /etc/yggdrasil/admin/backup
_backup_configs() {
	local -r backdir="$confdir"/admin/backup
	(( $# < 1 )) && return 0
	local f
	for f in "$@"; do
		[[ -f /etc/"$f" ]] || continue
		install -D /etc/"$f" "${backdir}/${f}"
	done
}

post_install() {
	local -r confdir="/etc/yggdrasil"
	local -r configs=(
		aurutils/aur-chroot.conf
		aurutils/pacman-x86_64.conf
		aurutils/makepkg-x86_64.conf
	)
	_backup_configs "${configs[@]}"
	ln -sf "$confdir"/aur-chroot.conf     /etc/aurutils/aur-chroot.conf
	ln -sf "$confdir"/pacman-x86_64.conf  /etc/aurutils/makepkg-x86_64.conf
	ln -sf "$confdir"/makepkg-x86_64.conf /etc/aurutils/makepkg-x86_64.conf

	install -d /var/cache/pacman/custom -o dn
	repo-add /var/cache/pacman/custom/custom.db.tar.zst
	chown dn:dn /var/cache/pacman/custom/*
	sed -i 's|^#\(\[custom\]\)$|\1|'                               "$confdir"/pacman.conf 2>/dev/null
	sed -i 's|^#\(SigLevel = Required DatabaseOptional\)$|\1|'     "$confdir"/pacman.conf 2>/dev/null
	sed -i 's|^#\(Server = file:///var/cache/pacman/custom\)$|\1|' "$confdir"/pacman.conf 2>/dev/null
}
