# /etc/samba/smb.conf

[global]
	workgroup = WORKGROUP
	server string = Valhalla File Server
	server role = standalone
	map to guest = never
	hosts allow = <IP prefix: ie 192.168.0.>
	hosts deny = ALL
	logging = systemd
	log level = 1
	load printers = no
	disable spoolss = yes

[<share>]
	path = /share/<path>
	comment = <path> Directory
	guest ok = No
	writable = Yes
	create mask = 0664
	force create mode = 0664
	directory mask = 2775
	force directory mode = 2775
	force user = media
	force group = media

