#!/hint/bash

post_install() {
	cat /etc/yggdrasil/motd/50-* >> /etc/motd
	cat /usr/share/yggdrasil/loader-example-lts.conf > /boot/loader/loader.conf

	systemctl enable sshd.service
	bootctl set-default ""

	install -D /etc/zfs/zed.d/zed.rc /etc/yggdrasil/valhalla/backup/zed.rc
	ln -sf /etc/yggdrasil/zed.rc     /etc/zfs/zed.d/zed.rc

	grep -q 'valhalla' /etc/hostname &&
		sed -i 's/HOSTNAME/VALHALLA/' /etc/motd
	grep -q 'folkvangr' /etc/hostname &&
		sed -i 's/HOSTNAME/ ASGARD /' /etc/motd
}
