#!/hint/bash

# Copies existing, hopefully known-good, configs to /etc/yggdrasil/base/backup
_backup_configs() {
	local -r backdir="$confdir"/base/backup

	(( $# < 1 )) && return 0
	local f
	for f in "$@"; do
		[[ -f /etc/"$f" ]] || continue
		install -D /etc/"$f" "${backdir}/${f}"
	done
}

# Sets up locale settings, including defining and creating as needed
_generate_locale() {
	ln -sf /usr/share/zoneinfo/America/Toronto /etc/localtime
	localedef -i /usr/share/i18n/locales/en_CA_24 -f UTF-8 en_CA_24.UTF-8

	local -r locales=( "en_CA.UTF-8" "en_US.UTF-8" )
	local locale
	for locale in "${locales[@]}"; do
		sed -i "s/^#${locale}/${locale}/" /etc/locale.gen
	done
	grep -q 'en_CA_24' /etc/locale.gen &>/dev/null || 
		echo "en_CA_24.UTF-8 UTF-8" >> /etc/locale.gen
	locale-gen
}

# Updates /etc/bash.bashrc so XDG directories are respected
_update_bashrc() {
	local -r bashrc_marker='# yggdrasil-specific bash.bashrc config'
	grep -Fqx -- "$bashrc_marker" /etc/bash.bashrc 2>/dev/null && return 0
	{
		printf '\n%s\n' "$bashrc_marker"
		printf '[[ -d "$HOME"/.config/shell/bash ]]        && export BDOTDIR="$HOME"/.config/shell/bash\n'
		printf '[[ -f "${BDOTDIR:-${HOME}}"/.bash_login ]] && source "${BDOTDIR:-${HOME}}"/.bash_login\n'
		printf '[[ -f "${BDOTDIR:-${HOME}}"/.bashrc ]]     && source "${BDOTDIR:-${HOME}}"/.bashrc\n'
	} >> /etc/bash.bashrc
}

post_install() {
	_generate_locale
	_update_bashrc

	[[ -e /.arch-chroot ]] || useradd -m -G wheel -s /usr/bin/zsh dn

	local -r confdir="/etc/yggdrasil"
	local configs=(
		issue
		locale.conf
		makepkg.conf
		mkinitcpio.conf
		pacman.conf
		vconsole.conf
	)
	_backup_configs "${configs[@]}"
	ln -sf yggdrasil/issue           /etc/issue
	ln -sf yggdrasil/locale.conf     /etc/locale.conf
	ln -sf yggdrasil/makepkg.conf    /etc/makepkg.conf
	ln -sf yggdrasil/mkinitcpio.conf /etc/mkinitcpio.conf
	ln -sf yggdrasil/pacman.conf     /etc/pacman.conf
	ln -sf yggdrasil/vconsole.conf   /etc/vconsole.conf

	systemctl enable pcscd.socket
	systemctl enable mirrorupdate.timer

	cp /etc/yggdrasil/motd/10-base /etc/motd
}

post_upgrade() {
	_generate_locale
}
